BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBB                 BBBBBBBBBBBBBBBB
BBBBBBBBBBB                 BBBBBBBBBBBBBBBB
BBBBBBBBBBB                 BBBBBBBBBBBBBBBB
BBBBBBBBBBB                 BBBBBBBBBBBBBBBB
BBBBBBBBBBB                 BBBBBBBBBBBBBB
BBBBBBBBBBB                 BBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBB                 BBBBBBBBBBB
BBBBBBBBBBB                 BBBBBBBBBBBBBB
BBBBBBBBBBB                 BBBBBBBBBBBBBBBB
BBBBBBBBBBB                 BBBBBBBBBBBBBBBB
BBBBBBBBBBB                 BBBBBBBBBBBBBBBB
BBBBBBBBBBB                 BBBBBBBBBBBBBBBB
BBBBBBBBBBB                 BBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
                IIIIIIIIIIIIII
                IIIIIIIIIIIIII
                IIIIIIIIIIIIII
                IIIIIIIIIIIIII
                IIIIIIIIIIIIII
                IIIIIIIIIIIIII
                IIIIIIIIIIIIII
                IIIIIIIIIIIIII
                IIIIIIIIIIIIII
                IIIIIIIIIIIIII
                IIIIIIIIIIIIII
                IIIIIIIIIIIIII
                IIIIIIIIIIIIII
                IIIIIIIIIIIIII
                IIIIIIIIIIIIII
                IIIIIIIIIIIIII
                IIIIIIIIIIIIII
                IIIIIIIIIIIIII
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII